FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
# Arguments
ARG PB_ENVIRONMENT_TYPE

# Enviroment Variables
ENV PB_ENVIRONMENT_TYPE=${PB_ENVIRONMENT_TYPE}
WORKDIR /app

EXPOSE 80
EXPOSE 443


COPY . .
ENTRYPOINT ["dotnet", "TestApp.dll", "--urls=http://+:80/"]